require_dependency 'redmine_send_to_contacts/hooks/views_issues_hook'
require_dependency 'redmine_send_to_contacts/patches/issues_controller_patch'
require_dependency 'redmine_send_to_contacts/patches/mailer_patch'
